name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Replace with your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Start SSH agent and add key manually
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          eval $(ssh-agent -s)
          ssh-add private_key

      - name: Copy files to server
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ root@173.249.3.40:/var/www/yourapp

      - name: Create .env file on server
        run: |
          ssh -o StrictHostKeyChecking=no root@173.249.3.40 "echo 'ACCESS_KEY=${{ secrets.ACCESS_KEY }}' > /var/www/yourapp/.env"
          ssh -o StrictHostKeyChecking=no root@173.249.3.40 "echo 'SECRET_KEY=${{ secrets.SECRET_KEY }}' >> /var/www/yourapp/.env"
          ssh -o StrictHostKeyChecking=no root@173.249.3.40 "echo 'USER_NAME=${{ secrets.USER_NAME }}' >> /var/www/yourapp/.env"
          ssh -o StrictHostKeyChecking=no root@173.249.3.40 "echo 'PASSWORD=${{ secrets.PASSWORD }}' >> /var/www/yourapp/.env"

      - name: Install dependencies on server
        run: ssh -o StrictHostKeyChecking=no root@173.249.3.40 "cd /var/www/yourapp && npm install --production"

      - name: Restart application
        run: ssh -o StrictHostKeyChecking=no root@173.249.3.40 "pm2 restart all || pm2 start /var/www/yourapp/index.js --name yourapp"
